name: Speedrun
version: 1.0
main: com.github.cresc28.speedrun.Speedrun
authors: [cresc28]
description: SpeedrunPlugin

commands:
  course:
    description: Make Speedrun cource
    usage: /course [add/remove] [start/end] [name] or /course list
