name: Speedrun
version: 1.0
main: com.github.cresc28.speedrun.Speedrun
authors: [cresc28]
description: SpeedrunPlugin

commands:
  course:
    description: Set speedrun course
    usage: /course <add|remove> <start|end|via_point> <name> or /course list
    permission: speedrun.course
    permission-message: "このコマンドを使用する権限がありません。"

  cp:
    description: set checkpoint
    usage: /cp <name> or /cp remove <name> or /cp list
    permission: speedrun.cp
    permission-message: "このコマンドを使用する権限がありません。"

  top:
    description: view records
    usage: /top <コース名> [dup] [detail] [above] [何位まで表示するか(最大30)] [player]

  record:
    description: manipulate records
    usage: /record <add|remove|removeAll>

permissions:
  speedrun.course:
    description: /courseの使用制限
    default: op

  speedrun.cp:
    description: /cpの使用制限
    default: op

  speedrun.record.add:
    description: 記録を追加できる
    default: op

  speedrun.record.remove:
    description: 記録を一つ削除できる
    default: op

  speedrun.record.removeAll:
    description: ある記録をすべて削除する
    default: op