name: Speedrun
version: 1.0
main: com.github.cresc28.speedrun.Speedrun
authors: [cresc28]
description: SpeedrunPlugin

commands:
  course:
    description: Set speedrun course
    usage: /course <add|remove> <start|end> <name> or /course list
    permission: speedrun.course
    permission-message: "このコマンドを使用する権限がありません。"

  cp:
    description: set checkpoint
    usage: /cp <name> or /cp remove <name> or /cp list
    permission: speedrun.cp
    permission-message: "このコマンドを使用する権限がありません。"

  top:
    description: view records
    usage: /top <コース名> [dup] [detail] [above] [何位まで表示するか(最大30)] [player]

permissions:
  speedrun.course:
    description: /courseの使用制限
    default: op

  speedrun.cp:
    description: /cpの使用制限
    default: op