name: Speedrun
version: 1.0
main: com.github.cresc28.speedrun.Speedrun
authors: [cresc28]
description: SpeedrunPlugin

commands:
  parkour:
    description: Make Speedrun cource
    usage: /parkour [add/remove] [start/end] [name] or /parkour list
